### ISSUE TITLE
關於在低解析度下默認展示不全問題

### ISSUE THREAD

**Issue by taranakineko** [LS-KR/CountDown-Day#6]
- 在低顯示器解析度下，開啟後默認展示的界面顯示不全
![Snipaste_2022-08-03_18-39-57](https://user-images.githubusercontent.com/55310629/182593061-6bfdcd40-17bc-431d-8cec-0a5c9de8fc13.png)
備註：測試用的裝置的顯示器解析度設置為1366x768 ~~（最高解析度了沒法再往大調qwq）~~ ，縮放比例100%
---
 - 開啟後右邊展示的是藍粉白樣式，且添加新的倒計時並點選後無變化，在系統設置裡切換為深色模式之後，右邊展示的是筆記本樣式，且無論再怎麼切換模式或關閉開啟程式，右邊一直展示的是筆記本樣式，而不是一開始的藍粉白樣式（除非通過系統設置裡的重設應用程式重設）
<video src="https://user-images.githubusercontent.com/55310629/182605344-d419824b-3c08-45fc-97e9-cfde8e395241.mp4"></video>

目前就找到了這兩個問題了，後面找到再添增下（

**Comment by LS-KR** [comment]
已修復
